### PR TITLE
bump polkadart-dependencies and switch from path to pub dev deps for sr25519 & polkadart_keyring

### PR DESCRIPTION
**Pull request by clangenb**
I went ahead and tried to integrate the new polkadart into my work and made the corresponding changes. :)

### CODE REVIEW

**Comment by leonardocustodio** [comment]
Can we get this one rebased and also check the CI error?

**Comment by clangenb** [comment]
Yes , I will do that so soon. The CI error is because of github server errors. I suspect that a rerun will solve the issue.

**Comment by clangenb** [comment]
Ah sorry, you are right there seems to be another error now.

**Review by leonardocustodio — APPROVED** [review]
thank you for the contribution :)

**Pull request merged**
