### PR TITLE
Update reuseable_workflow.yml

### PR DESCRIPTION
**Pull request by leonardocustodio**

### CODE REVIEW

**Comment by justkawal** [comment]
The code coverage will work by using the latest reuseable-workflow and specifying the current branch name after @ in test.yml in place of feature/CI-CD

**Comment by leonardocustodio** [comment]
Feel free to update ;)

**Comment by leonardocustodio** [comment]
Hmmm I believe @Lohann actions are over :laughing:

**Comment by leonardocustodio** [comment]
That seems wrong, before we had different percentages for each project. Now all of them are the same. I believe it is getting the same coverage file for all of them.

**Comment by justkawal** [comment]
> That seems wrong, before we had different percentages for each project. Now all of them are the same. I believe it is getting the same coverage file for all of them.

Yes, I looked into it, I was trying to optimise the speed by making tests all in single run and formatting in single run, but it took 1 minute more than before.

**Review by Lohann — APPROVED** [review]

**Pull request merged**
