### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justkawal**
Update Substrate metadata Readme

### CODE REVIEW

**Comment by justkawal** [comment]
@leonardocustodio @Lohann Can you please review it too ?

**Review by Lohann — APPROVED** [review]

**Comment by Lohann** [comment]
did you updated this PR with latest main? for some reason it doesn't run the CI checks

**Comment by justkawal** [comment]
> did you updated this PR with latest main? for some reason it doesn't run the CI checks

Yes 💯

**Comment by Lohann** [comment]
Ok.. I see the issue, is this on `tests.yml`:
```yml
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
```

**Comment by Lohann** [comment]
Once you only changed md files in this PR, it doesn't run the CI checks

**Comment by leonardocustodio** [comment]
Not an issue, it was intended to do that, no reason to run tests if no code was changed. This saves GH actions running time.

**Comment by Lohann** [comment]
@leonardocustodio the issue is that the PR got blocked from merging, because the required CI checks haven't passed, maybe there's a way to ignore some CI checks for PR's that only update the MD files.

**Comment by leonardocustodio** [comment]
Link check should still run, didn't it run?

**Comment by leonardocustodio** [comment]
Also checks only show that as it is supposed to be
image

**Comment by leonardocustodio** [comment]
But we can test again in a next PR to check what might have happened

**Pull request merged**
